#!/bin/sh
echo starting protein_info_service server.
export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg
export SERVICE=protein_info_service
export SERVICE_DIR=$KB_TOP/services/$SERVICE
#uncomment to debug: export STARMAN_DEBUG=1
$KB_RUNTIME/bin/starman --listen :7057 --pid $SERVICE_DIR/service.pid --daemonize \
  --access-log $SERVICE_DIR/log/access.log \
  --error-log $SERVICE_DIR/log/error.log \
  $KB_TOP/lib/ProteinInfoService.psgi
echo protein_info_service server is listening on port 7057.

